### ISSUE TITLE
Pulling binary for Maven role times out when user is connected to the VPN

### ISSUE THREAD

**Issue by mkhandep** [rajasoun/jumpstart#1]
Steps to reproduce: 
1. Ensure you are connected to the VPN
2. Comment all roles in the playbook.yml except for Maven
3. Do a $ vagrant provision

Expect:
Maven binary download time out in the console
TASK [maven : Download maven] **************************************************
Sunday 19 March 2017  04:07:33 -0700 (0:00:00.348)       0:00:00.998 **********
fatal: [vagrant-vm]: FAILED! => {"changed": false, "failed": true, "msg": "failed to create temporary content file: timed out"}
        to retry, use: --limit @/ck/playbook.retry

**Comment by rajasoun** [comment]
Thanks, @mkhandep.
One Possible Fix is to increase the Timeout in ansible.cfg. 

Going To Test It - If it fixed will close the Issue.

**Comment by rajasoun** [comment]
Issue Fixed. Pending Validation on Windows
