### ISSUE TITLE
Controller VM provisioning results in error

### ISSUE THREAD

**Issue by mkhandep** [rajasoun/jumpstart#2]
Trying to provision 'controller' vm (on Windows 10) using $ vagrant provision controller 
==> controller: Running provisioner: ansible_local...
    controller: Running ansible-playbook...
cd /ck/jumpstart && PYTHONUNBUFFERED=1 ANSIBLE_FORCE_COLOR=true ansible-playbook --limit="all" --inventory-file=ansible/inventory/topology -v --vault-password-file=/secrets/.vault_pass playbook.yml
Using /ck/jumpstart/ansible.cfg as config file
ERROR! Problem running vault password script / s e c r e t s / . v a u l t _ p a s s ([Errno 8] Exec format error). If this is not a script, remove the executable bit from the file.
Ansible failed to complete successfully. Any error output should be visible above. Please fix these errors and try again.

**Comment by rajasoun** [comment]
Thanks, @mkhandep. 
Fixed the Problem.

Route Cause:
On Windows Mounted folders by default make all files as executable.

Fix:
    config.vm.synced_folder 'secrets', '/secrets', mount_options: ['dmode=0755,fmode=0644']
    config.vm.synced_folder 'vagrant/keys', '/keys', mount_options: ['dmode=755,fmode=0400']
