### ISSUE TITLE
Synch folders not restricted to vagrant-vm as specified in config.yml file

### ISSUE THREAD

**Issue by mkhandep** [rajasoun/jumpstart#3]
The config.yml file in /jumpstart/vagrant/scripts folder has specified sync folders for vagrant-vm vm.
Sync folders are also getting mounted (synced) for controller vm, which may not be intended.
Behaviour noted on Windows 10.

**Comment by rajasoun** [comment]
Thanks, @mkhandep. 
Code needs to be refactored. Will keep it Open

**Comment by rajasoun** [comment]
Refactored For Readability.
